version: '2'

services:
  web:
    image: nginx:1.11
    container_name: fy_web
    volumes:
      - ./conf/nginx.template:/etc/nginx/conf.d/mysite.template
      - ./app:/usr/www
    ports:
      - '80:80'
    environment:
      - NGINX_ROOT=/usr/www
      - FPM_LISTEN=fpm:9000
    command: /bin/bash -c "envsubst '$$FPM_LISTEN $$NGINX_ROOT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - fpm
      - mysql
    links:
      - fpm:fpm
      - mysql:mysql

  fpm:
    build:
      context: ./dockerfile/php
      dockerfile: fpm-7.0.12
    image: fyzzy1943/fpm:7.0.12
    container_name: fy_fpm
    volumes:
      - ./app:/usr/www
      - ./conf/php.ini:/usr/local/lib/php.ini
    expose:
      - '9000'

  mysql:
    image: mysql:5.7.16
    container_name: fy_mysql
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sheep
    expose:
      - '3306'
